"""凍結輸入 bundle（I-100）的公開 API。

⚠️ **這一層是穩定介面**：`evaluation.py` 只透過這裡呼叫，⛔ 不直接 import 子模組的私有名稱。
反過來，**本 package 一律不 import `evaluation.py`**——那會製造循環依賴，而且 bundle 的
規格本來就不該依賴 replay 的流程。

分工：

* `canonical`——canonical JSON／gzip 與內容指紋（bundle 身分的唯一來源）
* `calendar`——TWSE 交易日曆的取得、解析、正規化與 frozen override
* `provenance`——執行身分（模組 hash、image digest、git worktree、argv）
* `publish`——`renameat2(RENAME_NOREPLACE)` 的整包原子發布
* `bundle`——bundle 規格、產生與載入
"""
from __future__ import annotations

from .artifacts import (
    AFTER_ARTIFACT_NAME,
    AFTER_KIND,
    ARTIFACT_SCHEMA_VERSION,
    CANDIDATE_FIELD,
    COHORT_KIND,
    COHORT_MANIFEST_NAME,
    COMPARISON_ARTIFACT_NAME,
    COMPARISON_KIND,
    REPORT_KIND,
    REPORT_NAME,
    ArtifactError,
    assert_matches_bundle,
    assert_same_keys,
    assert_unique_keys,
    build_after_artifact,
    build_cohort_manifest,
    build_comparison_artifact,
    build_report,
    candidate_keys,
    compare_rows,
    load_artifact,
    prepare_output_dir,
    publish_artifacts,
    row_key,
    validate_after_artifact,
    validate_candidate_flags,
    validate_cohort_manifest,
)
from .bundle import (
    MANIFEST_NAME,
    MANIFEST_SCHEMA_VERSION,
    MANIFEST_SHA_NAME,
    PAYLOAD_FILES,
    BundleError,
    LoadedBundle,
    PublishOutcome,
    build_manifest,
    compute_bundle_id,
    emit_bundle,
    load_bundle,
    render_payloads,
)
from .calendar import (
    CALENDAR_SCHEMA_VERSION,
    CALENDAR_SOURCE,
    ROW_TYPES,
    TWSE_CALENDAR_URL,
    CalendarError,
    TradingCalendar,
    build_calendar_online,
    build_calendar_payload,
    classify_calendar_row,
    load_frozen_calendar,
    parse_calendar_date,
    validate_calendar_payload,
)
from .canonical import (
    CanonicalError,
    canonical_gzip_bytes,
    canonical_json_bytes,
    content_hash8,
    sha256_file,
    sha256_hex,
    symbols_hash8,
)
from .provenance import (
    PROJECT_MODULE_NAMES,
    PROJECT_MODULE_PREFIXES,
    ProvenanceError,
    build_provenance,
    is_project_module,
    pip_freeze_sha256,
    project_module_hashes,
)
from .publish import (
    EXIT_ABORT,
    EXIT_DURABILITY_UNCONFIRMED,
    DurabilityUnconfirmed,
    NoClobberUnsupported,
    PublishError,
    probe_no_clobber,
    rename_noreplace,
)

__all__ = [
    "AFTER_ARTIFACT_NAME",
    "AFTER_KIND",
    "ARTIFACT_SCHEMA_VERSION",
    "ArtifactError",
    "BundleError",
    "CANDIDATE_FIELD",
    "COHORT_KIND",
    "COHORT_MANIFEST_NAME",
    "COMPARISON_ARTIFACT_NAME",
    "COMPARISON_KIND",
    "REPORT_KIND",
    "REPORT_NAME",
    "assert_matches_bundle",
    "assert_same_keys",
    "assert_unique_keys",
    "build_after_artifact",
    "build_cohort_manifest",
    "build_comparison_artifact",
    "build_report",
    "candidate_keys",
    "compare_rows",
    "load_artifact",
    "prepare_output_dir",
    "publish_artifacts",
    "row_key",
    "validate_after_artifact",
    "validate_candidate_flags",
    "validate_cohort_manifest",
    "CALENDAR_SCHEMA_VERSION",
    "CALENDAR_SOURCE",
    "CalendarError",
    "ROW_TYPES",
    "TWSE_CALENDAR_URL",
    "TradingCalendar",
    "build_calendar_online",
    "build_calendar_payload",
    "classify_calendar_row",
    "load_frozen_calendar",
    "parse_calendar_date",
    "validate_calendar_payload",
    "CanonicalError",
    "DurabilityUnconfirmed",
    "EXIT_ABORT",
    "EXIT_DURABILITY_UNCONFIRMED",
    "LoadedBundle",
    "MANIFEST_NAME",
    "MANIFEST_SCHEMA_VERSION",
    "MANIFEST_SHA_NAME",
    "NoClobberUnsupported",
    "PAYLOAD_FILES",
    "PROJECT_MODULE_NAMES",
    "PROJECT_MODULE_PREFIXES",
    "ProvenanceError",
    "build_provenance",
    "is_project_module",
    "pip_freeze_sha256",
    "project_module_hashes",
    "PublishError",
    "PublishOutcome",
    "build_manifest",
    "canonical_gzip_bytes",
    "canonical_json_bytes",
    "compute_bundle_id",
    "content_hash8",
    "emit_bundle",
    "load_bundle",
    "probe_no_clobber",
    "rename_noreplace",
    "render_payloads",
    "sha256_file",
    "sha256_hex",
    "symbols_hash8",
]
